const N = ['Order activation','Engineering & design','Procurement','Manufacturing','Shipping & installation','FAT and commissioning'];
const O = ['PM','Engineering','Procurement','Workshop','Logistics','Commissioning'];
const W = [0.06,0.16,0.25,0.28,0.15,0.1];
const ts = (d: string) => `${d}T09:00:00`;
const id = (...parts: string[]) => parts.join('__').replace(/[^a-zA-Z0-9_:-]/g, '_');
const configs = [
  {
    n:'PRJ-2026-003',t:'IP Waterloo - AMR Waste Automation System',c:'RapidBond / International Paper Waterloo',pt:'machine',cx:'high',rl:'medium',st:'engineering_review',hs:71,v:502700,b:301331,a:82450,inv:150810,paid:75405,mt:40,ma:36,
    scope:'4 AMR waste-handling system with 26 cages, trident conveyors, weighing station, Wi-Fi coverage, commissioning and production start-up.',
    deliv:'AMR equipment, cages, trident conveyors, electrical integration, route scan, commissioning, training and EDAR-driven execution.',
    excl:'Customer workshop support, cranes/lifts, utilities outside scope, extra requested days, mirrored HMI and software ownership transfer.',
    pay:'15% PO; 15% final engineering; 40% shipping notice; 15% receipt in Waterloo; 15% commissioning validation.',inc:'DDU',war:'2 years.',pen:'Control through EDAR, frozen layouts and agreed validation gates.',cust:'custom-engineered',eng:'high',
    req:'RapidBond is the intermediary. Engineering review is in progress; pending layouts, charger relocation, cycle time and Wi-Fi optimization must close before release.',
    src:'C:\\Users\\isena\\Documents\\INGECART\\COMMERCIAL\\PROYECTOS\\IP AMR PROJECT\\IP AMR SYSTEM WATERLOO.docx\nC:\\Users\\isena\\Documents\\INGECART\\COMMERCIAL\\PROYECTOS\\IP AMR PROJECT\\Engineering Decision & Action Register.txt\nC:\\Users\\isena\\Documents\\INGECART\\COMMERCIAL\\PROYECTOS\\IP AMR PROJECT\\COSTES SISTEM AMR DESPERDICIO IP WATERLOO 28 04  2026.xlsx',
    dep:'Updated IP drawings, final layout validation, engineering freeze, manufacturing release, FAT, shipment, installation and SAT.',notes:'Source D-26085 (2026-04-23). Cost workbook baseline 301,331 EUR. Functional description and EDAR linked for execution follow-up.',created:'2026-04-23',start:'2026-07-13',end:'2026-12-15',prio:'engineering_validation',next:'Final layout validation',
    phases:[
      ['completed','2026-04-23','2026-05-05',0.18,100,['Confirm D-26085 baseline','Validate PO/payment path','Open EDAR'],['Commercial handoff','Project charter'],['Intermediated communication']],
      ['in_progress','2026-05-06','2026-08-15',0.63,62,['Receive updated plant layouts','Validate zones and RDC','Freeze routes and chargers'],['EDAR review cadence','Customer layout approval'],['Layout changes','Signal integration rework']],
      ['pending','2026-08-18','2026-09-30',0,0,['Release AMR orders','Confirm Sifise and cage suppliers','Secure Wi-Fi hardware'],['Long-lead confirmation'],['Vendor lead time']],
      ['pending','2026-10-01','2026-11-05',0,0,['Fabricate cages','Assemble trident conveyors','Workshop trials'],['Internal FAT readiness'],['Workshop capacity']],
      ['pending','2026-11-06','2026-12-01',0,0,['Issue shipping notice','Confirm site access','Coordinate support resources'],['Equipment receipt'],['Site readiness']],
      ['pending','2026-12-02','2026-12-15',0,0,['Commission AMRs','Train operators','Close punch list'],['SAT sign-off'],['Cycle-time tuning']],
    ],
    ms:[
      ['contract','PO / commercial authorization','RapidBond commercial baseline accepted.','2026-04-23','2026-04-23','completed','Order activation',75405,15,true,true,'Sales',['D-26085 offer','Commercial acceptance']],
      ['design','Final engineering package released','Final layout and EDAR actions closed.','2026-08-15',null,'pending','Engineering & design',75405,15,false,false,'Engineering',['EDAR register','Final layouts']],
      ['procurement','Shipping notification','Equipment ready and shipping notice issued.','2026-11-05',null,'pending','Manufacturing',201080,40,false,false,'Procurement',['Supplier confirmations','Shipping pack']],
      ['installation','Equipment received in Waterloo','Receipt at customer plant.','2026-11-20',null,'pending','Shipping & installation',75405,15,false,false,'Logistics',['Delivery note','Site readiness']],
      ['final','Commissioning and customer validation','Production validation complete.','2026-12-15',null,'pending','FAT and commissioning',75405,15,false,false,'Commissioning',['SAT protocol','Training record']],
    ],
    risks:[['Final layout dependency','Engineering freeze depends on updated IP drawings and final layout validation.','engineering','high','high',84,'Maintain EDAR and weekly decision review.','Release by area if required.','Engineering','open'],['AMR route performance','Cycle time and charger location may require additional optimization.','automation','medium','high',73,'Validate routes using digital twin and sequence summary.','Add buffer positions or revise chargers.','Automation','monitoring'],['Intermediated customer communication','RapidBond can delay engineering clarifications and approvals.','commercial','medium','medium',61,'Keep direct technical action log and approval deadlines.','Escalate unresolved approvals to steering call.','PM','open']],
    gates:[['Commercial baseline','passed','2026-04-23','2026-04-23','D-26085 accepted and EDAR opened.','Sales'],['Engineering freeze','pending','2026-08-15',null,'Final layouts and open EDAR actions closed.','Engineering'],['Manufacturing release','pending','2026-09-30',null,'AMRs, cages and conveyors released.','Procurement'],['Shipment readiness','pending','2026-11-05',null,'Packing, shipping documents and site plan approved.','Logistics'],['SAT / customer acceptance','pending','2026-12-15',null,'Production validation achieved in Waterloo.','Commissioning']],
    costs:[['engineering','Engineering and EDAR validation',90399,51800],['procurement','KUKA AMRs and supplier packages',166431,0],['manufacturing','Cages, trident conveyors and workshop build',102500,30650],['shipping','Freight, unloading and site mobilization',24001,0],['commissioning','20-day installation, start-up and training',18000,0]],
  },
  {
    n:'PRJ-2026-005',t:'Cascades Piscataway - Dual Robotic Palletizer',c:'RapidBond / Cascades Piscataway',pt:'machine',cx:'high',rl:'high',st:'in_progress',hs:63,v:1052000,b:820560,a:246000,inv:420800,paid:210400,mt:22,ma:19,
    scope:'Dual robotic palletizer with conveyors, bundle stacker, 2 KUKA robotic units, pad paper handling, 4-side squaring, safety and control integration.',
    deliv:'Mechanical/electrical design, robotic palletizer system, FAT package, transport, installation, training and contract control with RapidBond/Cascades.',
    excl:'Civil works, local taxes, unloading aids beyond agreed forklift support and non-approved scope changes.',
    pay:'Main quote IC-DR-12.25 v3 issued DDU; monitor contractual milestones against approved agreement.',inc:'DDU Barcelona to Piscataway, NJ',war:'12 months after final acceptance.',pen:'Legal liability, consequential damages, LDs, tariff exposure and acceptance mechanics require active control.',cust:'custom-engineered',eng:'high',
    req:'Sale is via RapidBond but direct technical interlocution with Cascades exists. Project needs aligned legal structure, approved engineering baseline and coordinated installation planning.',
    src:'C:\\Users\\isena\\Documents\\INGECART\\COMMERCIAL\\PROYECTOS\\CASCADES\\PALLETIZER 2026\\Proposal Cascades - Dual Robotic Palletizer IC-DR-12.25 v3.pdf\nC:\\Users\\isena\\Documents\\INGECART\\COMMERCIAL\\PROYECTOS\\CASCADES\\PALLETIZER 2026\\Notas estado projecto 12 05 2026.docx',
    dep:'Contract closure, approved engineering docs, supplier release, FAT sign-off, sea freight coordination, site readiness and final acceptance certificate.',notes:'IC-DR-12.25 v3 shows 1,027,567 EUR DDU plus later commercial updates. Keep legal/commercial risk under weekly review.',created:'2026-06-16',start:'2026-06-16',end:'2026-11-30',prio:'contract_and_execution_control',next:'Engineering release',
    phases:[['completed','2026-06-16','2026-06-30',0.15,100,['Validate commercial baseline','Align RapidBond/Cascades roles','Open risk log'],['Order baseline','Kickoff alignment'],['Contractual exposure']],['in_progress','2026-07-01','2026-08-20',0.35,68,['Freeze robot interfaces','Validate layouts','Prepare FAT package'],['Customer drawing approval'],['Late changes','Contract dependencies']],['in_progress','2026-08-01','2026-09-20',0.39,42,['Release robots','Release safety and controls','Track long-lead items'],['Supplier confirmations'],['Supply delay','Tariffs']],['pending','2026-09-15','2026-10-31',0,0,['Mechanical assembly','Controls wiring','Factory tests'],['FAT readiness'],['Integration defects']],['pending','2026-11-01','2026-11-20',0,0,['Freight booking','Customs pack','Site access plan'],['Shipping release'],['Port or site delays']],['pending','2026-11-21','2026-11-30',0,0,['Execute FAT','Commission on site','Close acceptance'],['Final acceptance certificate'],['Acceptance criteria dispute']]],
    ms:[['contract','Commercial / contract baseline','Main project baseline aligned with RapidBond and Cascades.','2026-06-20','2026-06-20','completed','Order activation',105200,10,true,true,'Sales',['IC-DR-12.25 v3','Contract status update']],['design','Engineering freeze','Layouts and interfaces approved for build.','2026-08-20',null,'pending','Engineering & design',263000,25,false,false,'Engineering',['Approved layout','Engineering documents']],['procurement','Material readiness','Long-lead items and robots ready for assembly.','2026-09-25',null,'pending','Procurement',315600,30,false,false,'Procurement',['Supplier pack','Procurement release']],['factory','FAT complete','FAT package executed and signed.','2026-11-05',null,'pending','Manufacturing',210400,20,false,false,'QA',['FAT protocol','Quality dossier']],['final','Site acceptance','Installation, commissioning and acceptance closed.','2026-11-30',null,'pending','FAT and commissioning',157800,15,false,false,'Commissioning',['SAT certificate','Training record']]],
    risks:[['Contractual risk allocation','Current structure exposes RBI/Ingecart to EPC-like legal and financial risk.','contract','high','high',90,'Track liability, LDs, tariffs and acceptance terms weekly.','Escalate unresolved clauses before manufacturing release.','Management','open'],['Acceptance mechanics','Acceptance criteria and certificate signature must be fully agreed.','commercial','medium','high',76,'Lock FAT/SAT criteria in approved documentation.','Use joint punch-list and interim acceptance.','PM','monitoring'],['Tariff / transport exposure','Sea transport and tariff variability can affect delivery and margin.','logistics','medium','medium',62,'Confirm transport booking and customs path early.','Freeze shipment windows with alternatives.','Logistics','open']],
    gates:[['Commercial baseline','passed','2026-06-20','2026-06-20','Project opened with commercial/legal baseline.','Sales'],['Engineering release','pending','2026-08-20',null,'All palletizer interfaces and layouts released.','Engineering'],['Procurement release','pending','2026-09-25',null,'Robots, controls and mechanical supply released.','Procurement'],['FAT approval','pending','2026-11-05',null,'Factory tests signed before shipment.','QA'],['Final acceptance','pending','2026-11-30',null,'Site acceptance certificate signed.','Commissioning']],
    costs:[['engineering','Robotic engineering and layouts',131290,86000],['procurement','Robots, conveyors, squaring and safety',482000,96000],['manufacturing','Assembly and FAT preparation',127270,62000],['shipping','Transport and packaging',64000,0],['commissioning','Installation, hotels, flights and food',93000,2000]],
    changes:[['CO-10433','EVOL Outfeed Conveyor add-on','Additional PO for Cascades Piscataway outfeed conveyor.','approved',101482,101482,14,'Additional material handling scope']],
  },
  {
    n:'PRJ-2026-006',t:'Cascades Piscataway - EVOL Outfeed Conveyor Change Order',c:'RapidBond / Cascades Piscataway',pt:'machine',cx:'medium',rl:'medium',st:'planning',hs:74,v:101482,b:79156,a:12000,inv:81185.6,paid:0,mt:22,ma:20,
    scope:'Additional EVOL outfeed conveyor system with installation coordinated by Ingecart and RapidBond.',deliv:'Outfeed conveyor, mechanical/electrical docs, PLC program, HMI backup, operation/maintenance manuals and FAT docs when applicable.',excl:'Main conveyor dismantling, non-approved electrical modifications and non-contracted travel changes.',pay:'80% on PO issuance (Net 90); 20% on installation and final acceptance (Net 90).',inc:'DAP / Facility Piscataway NJ',war:'12 months after final acceptance.',pen:'Scope, schedule or commercial changes require written authorization from RapidBond.',cust:'configured',eng:'medium',req:'Conveyor must remain compatible with the main robotic palletizer project. Customer forklift support is required at unloading.',src:'C:\\Users\\isena\\Documents\\INGECART\\COMMERCIAL\\PROYECTOS\\CASCADES\\PALLETIZER 2026\\PURCHASE ORDER RBI-10433 - INGECART EXIT CONVEYOR EVOL @ CASCADES 07.26.pdf\nC:\\Users\\isena\\Documents\\INGECART\\COMMERCIAL\\PROYECTOS\\CASCADES\\PALLETIZER 2026\\Operacion bandas a 90 ª Cascade.txt',dep:'Sea shipment, site unloading coordination, installation window and signed change control against main project.',notes:'PO-10433 dated 2026-06-18. Additional note references 7 labour days, flights, hotel, per diem, packaging and transport.',created:'2026-06-18',start:'2026-06-18',end:'2026-11-30',prio:'change_order_execution',next:'Installation planning',
    phases:[['completed','2026-06-18','2026-06-25',0.27,100,['Validate PO terms','Link with main project','Register change scope'],['PO baseline'],['Scope gap vs main project']],['in_progress','2026-06-26','2026-07-20',0.45,55,['Confirm conveyor geometry','Review electrical tie-in','Check compatibility'],['Approved interface drawing'],['Tie-in mismatch']],['pending','2026-07-21','2026-08-20',0,0,['Release packaging','Book transport','Confirm suppliers'],['Material readiness'],['Freight cost shift']],['pending','2026-08-21','2026-09-30',0,0,['Assembly','Internal check','Prepare manuals'],['Pre-shipment approval'],['Workshop overlap']],['pending','2026-10-01','2026-11-20',0,0,['Transport','Travel plan','Site coordination'],['Delivered to site'],['Site slot change']],['pending','2026-11-21','2026-11-30',0,0,['Functional validation','Final acceptance','Close documentation'],['Acceptance certificate'],['Acceptance dependency on main line']]],
    ms:[['contract','PO issued','PO-10433 issued by RapidBond / Cascades.','2026-06-18','2026-06-18','completed','Order activation',81185.6,80,true,false,'Sales',['PO-10433']],['design','Interface package approved','Conveyor tie-in package approved.','2026-07-20',null,'pending','Engineering & design',0,0,false,false,'Engineering',['Interface drawing']],['final','Installation and acceptance','Installation and acceptance signed.','2026-11-30',null,'pending','FAT and commissioning',20296.4,20,false,false,'Commissioning',['Acceptance certificate','As-built package']]],
    risks:[['Installation window coordination','Add-on conveyor installation must fit the main project schedule.','site','medium','high',70,'Coordinate installation window with RapidBond and main project team.','Split delivery and installation if site is not ready.','PM','open'],['Travel and freight extras','Flights, hotel, per diem and shared container assumptions may deviate.','logistics','medium','medium',58,'Track actual travel/freight vs note-based estimates.','Issue commercial approval for deviations.','Logistics','monitoring']],
    gates:[['PO baseline','passed','2026-06-18','2026-06-18','PO-10433 entered as approved change order.','Sales'],['Interface approval','pending','2026-07-20',null,'Mechanical/electrical interface released.','Engineering'],['Final acceptance','pending','2026-11-30',null,'Installation and customer acceptance closed.','Commissioning']],
    costs:[['engineering','Engineering and tie-in definition',12665,8800],['procurement','Conveyor materials and controls',42500,0],['shipping','Packaging and transport',12000,0],['installation','7-day installation labour and travel',11991,0]],
  },
  {
    n:'PRJ-2026-008',t:'Cascades Calgary - Phase 1 Transfer & Conveyor',c:'RapidBond / Cascades Calgary',pt:'machine',cx:'high',rl:'high',st:'engineering_review',hs:58,v:1397363,b:1116692.83,a:182000,inv:0,paid:0,mt:20,ma:15,
    scope:'Phase 1 transfer and automated conveyor package integrating three RDC outputs, second-pass machines, shipping conveyor and future AGV-ready trident interfaces.',deliv:'Automatic transfer car, automated conveyors, PLC logic, software coordination, engineering package, safety coordination and installation planning.',excl:'Phase 2 palletizing package, undefined civil modifications and future AGV expansion unless explicitly approved.',pay:'Commercial and engineering package under active definition; pricing evidence shows project-level sale and cost model pending closure.',inc:'To be confirmed with RapidBond / customer',war:'To be defined in final agreement.',pen:'Protect engineering prioritization and installation sequence through approved phased scope and layout freeze.',cust:'custom-engineered',eng:'high',req:'Phase 1 removes manual operator dependency and introduces software-coordinated transfer logic with measurable labour and throughput gains.',src:'C:\\Users\\isena\\Documents\\INGECART\\COMMERCIAL\\PROYECTOS\\CASCADES\\Cascades Calgary\\PROYECTO 2027 FASE 1\\CALGARY FASE 1.txt\nC:\\Users\\isena\\Documents\\INGECART\\COMMERCIAL\\PROYECTOS\\CASCADES\\Cascades Calgary\\PROYECTO 2027 FASE 1\\OFF-2026-135 Cascades Calgary Phase 1 Transfer & Conveyor Proposal.pdf\nC:\\Users\\isena\\Documents\\INGECART\\COMMERCIAL\\PROYECTOS\\CASCADES\\Cascades Calgary\\PROYECTO 2027 FASE 1\\Escandallo Costes FASE 1 CASCADES.xlsx',dep:'Customer layout validation, engineering prioritization, installation sequence agreement, cost alignment with RapidBond and phased release.',notes:'Cost workbook shows sale 1,397,363 EUR and cost baseline 1,116,692.83 EUR. Project is Phase 1 of a wider Calgary automation roadmap.',created:'2026-06-25',start:'2026-07-01',end:'2027-03-31',prio:'phase_definition_and_roi',next:'Customer layout validation',
    phases:[['completed','2026-07-01','2026-07-15',0.29,100,['Define Phase 1 limits','Align RapidBond route','Register ROI logic'],['Scope perimeter signed'],['Scope drift to future phases']],['in_progress','2026-07-16','2026-10-15',0.71,54,['Validate RDC outputs','Freeze transfer positions','Confirm AGV-ready trident logic'],['Customer layout approval','Signal list approval'],['Layout changes','Signal mismatches']],['pending','2026-10-16','2026-11-30',0,0,['Release transfer hardware','Release conveyor package','Confirm supplier schedule'],['Long-lead confirmation'],['Supplier capacity']],['pending','2026-12-01','2027-01-31',0,0,['Assembly','Internal test','Pre-FAT prep'],['Internal sequence validation'],['Integration complexity']],['pending','2027-02-01','2027-03-10',0,0,['Shipment plan','Site access plan','Installation slot'],['Site readiness'],['Operational interruption']],['pending','2027-03-11','2027-03-31',0,0,['Functional validation','Operator training','Performance tuning'],['Acceptance against phase objectives'],['Throughput tuning']]],
    ms:[['contract','Phase 1 technical baseline','Scope and layout baseline confirmed.','2026-07-15','2026-07-15','completed','Order activation',139736.3,10,false,false,'Sales',['OFF-2026-135','Calgary Phase 1 brief']],['design','Engineering package approved','Layouts and signal list approved.','2026-10-15',null,'pending','Engineering & design',349340.75,25,false,false,'Engineering',['Approved layouts','Signal requirements']],['procurement','Materials ready','Transfer and conveyor package released.','2026-11-30',null,'pending','Procurement',419208.9,30,false,false,'Procurement',['Procurement release','Supplier plan']],['factory','Factory validation','Internal validation and pre-shipment readiness.','2027-01-31',null,'pending','Manufacturing',279472.6,20,false,false,'QA',['Validation report']],['final','Commissioning & acceptance','Phase 1 accepted with stable automated flow.','2027-03-31',null,'pending','FAT and commissioning',209604.45,15,false,false,'Commissioning',['Acceptance report','Training pack']]],
    risks:[['Scope bleed to later phases','Phase 1 can absorb later requirements if boundaries are not controlled.','scope','high','high',88,'Freeze phase perimeter and track future items separately.','Convert extras into later phases/change orders.','PM','open'],['Signal and software integration','Existing production system interfaces and routing logic must be validated early.','automation','medium','high',76,'Close signal requirements and interface simulations before release.','Stage commissioning by machine cluster.','Automation','open'],['Operational change management','Moving from manual to automated transfer requires adoption support.','operations','medium','medium',64,'Prepare training and phased ramp-up with plant team.','Run assisted production period after SAT.','Commissioning','monitoring']],
    gates:[['Phase baseline','passed','2026-07-15','2026-07-15','Phase 1 scope and ROI baseline defined.','PM'],['Engineering release','pending','2026-10-15',null,'Layouts, signals and logic approved.','Engineering'],['Procurement release','pending','2026-11-30',null,'Transfer and conveyor package released.','Procurement'],['Factory validation','pending','2027-01-31',null,'Internal validation complete before shipment.','QA'],['Site acceptance','pending','2027-03-31',null,'Automated flow in Calgary stabilized and accepted.','Commissioning']],
    costs:[['engineering','Phase 1 engineering and software definition',178671,130000],['procurement','Transfer car and conveyors',644000,0],['manufacturing','Build and internal validation',162021.83,52000],['shipping','Shipment and installation preparation',80000,0],['commissioning','Commissioning and performance tuning',52000,0]],
  },
  {
    n:'PRJ-2026-009',t:'SAICA Pack Barcelona - Technical Audit',c:'SAICA Pack Barcelona',pt:'service',cx:'medium',rl:'low',st:'planning',hs:86,v:1122,b:720,a:0,inv:0,paid:0,mt:35,ma:0,
    scope:'Technical audit of the wet end of the Asitrade line: parallelism, paper tension, reel stand/splicer alignment and corrugator interface review.',deliv:'On-site audit visit, measurements, technical analysis, audit report, risk findings and preliminary corrective recommendations.',excl:'No corrective work, mechanical adjustments or machine modifications are included in the audit scope.',pay:'Time and materials: 95 EUR/h plant audit, 60 EUR/h internal analysis, 40 EUR/h report drafting, 0.70 EUR/km. Reference estimate 1,122 EUR.',inc:'N/A service project',war:'Diagnostic advisory service.',pen:'Keep hours and findings approved against actual work performed.',cust:'service',eng:'medium',req:'Short-cycle diagnostic intervention for SAICA Pack Barcelona, attn. Sr. Domingo. It should identify root causes and prioritize corrective actions.',src:'C:\\Users\\isena\\Documents\\INGECART\\COMMERCIAL\\PROYECTOS\\SAICA\\Oferta Servicios de Auditoría  OFF-2026-S100\\Oferta Servicios de Auditoría  OFF-2026-S100.pdf\nC:\\Users\\isena\\Documents\\INGECART\\COMMERCIAL\\PROYECTOS\\SAICA\\Oferta Servicios de Auditoría  OFF-2026-S100\\OFERTA AUDITORIO.txt',dep:'Visit scheduling, plant access, measurement window, technical review and report issuance.',notes:'Estimate based on 8h plant audit, 4h internal analysis, 2h report drafting and 60 km travel. This can unlock later corrective offers.',created:'2026-06-15',start:'2026-09-15',end:'2026-09-30',prio:'service_execution',next:'Audit visit scheduled',
    phases:[['in_progress','2026-09-15','2026-09-17',0.2,35,['Schedule audit visit','Confirm plant access','Prepare checklist'],['Customer confirmation'],['Visit delay']],['pending','2026-09-18','2026-09-18',0,0,['Parallelism check','Paper tension review','Alignment verification'],['Measurements captured'],['Access restrictions']],['pending','2026-09-18','2026-09-18',0,0,['Prepare measurement tools'],['Tools ready'],['None']],['pending','2026-09-19','2026-09-23',0,0,['Analyze measurements','Draft findings','Structure recommendations'],['Draft report'],['Insufficient evidence']],['pending','2026-09-24','2026-09-26',0,0,['Deliver report','Review findings'],['Customer receipt'],['Feedback delay']],['pending','2026-09-27','2026-09-30',0,0,['Agree next steps','Convert findings into actions','Define corrective path'],['Next-step agreement'],['No follow-up decision']]],
    ms:[['contract','Visit confirmed','Audit scope and date confirmed with SAICA.','2026-09-17',null,'pending','Order activation',0,0,false,false,'Sales',['Offer OFF-2026-S100']],['design','Audit executed','Plant audit and measurements completed.','2026-09-18',null,'pending','Engineering & design',760,68,false,false,'Engineering',['Audit checklist']],['final','Report delivered','Technical report delivered and reviewed.','2026-09-26',null,'pending','Shipping & installation',362,32,false,false,'PM',['Audit report']]],
    risks:[['Audit window dependency','Short service project depends on plant access and key line availability.','site','medium','medium',48,'Confirm visit slot and checklist before mobilization.','Split audit into shorter windows.','PM','open'],['Diagnostic scope expectations','Customer may expect corrective work beyond the diagnostic scope.','scope','medium','medium',52,'Reconfirm exclusions and convert corrections into follow-up proposals.','Issue separate corrective quotation.','Sales','monitoring']],
    gates:[['Visit readiness','pending','2026-09-17',null,'Customer date, access and checklist confirmed.','PM'],['Technical findings complete','pending','2026-09-23',null,'Analysis and findings validated internally.','Engineering'],['Report delivery','pending','2026-09-26',null,'Audit report delivered and reviewed with SAICA.','PM']],
    costs:[['engineering','Plant audit hours',760,0],['indirect','Internal analysis and report',320,0],['transport','Mileage',42,0]],
  },
  {
    n:'PRJ-2026-010',t:'Sterner Global / Mastercorr - Engineering Support',c:'Sterner Global / Mastercorr',pt:'service',cx:'high',rl:'medium',st:'in_progress',hs:69,v:180500,b:71921.13,a:11800,inv:36100,paid:0,mt:45,ma:38,
    scope:'Software engineering, electrical engineering and commissioning support for the Mastercorr equipment supplied by Ingecart.',deliv:'Software program, electrical wiring package in EPLAN, commissioning support, cable diagrams and deliverables in English.',excl:'Civil works, utilities to control cabinets, site lifting equipment, installation helpers, import taxes and undefined customer requirements.',pay:'20% advance; 30% at 60 days after milestone 1; 35% when deliverables are ready; 10% after acceptance test or four months after delivery if delayed by buyer.',inc:'Service / engineering scope',war:'Governed by offer 25-01-1787V1 service conditions.',pen:'Safety responsibilities and timing/specification documents must be attached contractually.',cust:'engineered service',eng:'high',req:'Project depends on clearly defined specifications, timing tables and attached contractual documents. Support scope includes software, electrical engineering and 4 weeks of start-up support.',src:'C:\\Users\\isena\\Documents\\INGECART\\COMMERCIAL\\PROYECTOS\\Sterner Global\\MASTERCORR\\Of. 25-01-1787V1 INGECART INGENIERIA INGETRANS280 rev ricardo.docx\nC:\\Users\\isena\\Documents\\INGECART\\COMMERCIAL\\PROYECTOS\\Sterner Global\\MASTERCORR\\Copy of PROYECTO VENTA POR MT 07 11 2024.xlsm',dep:'Attach final specifications contractually, lock timing tables, receive advance payment, close electrical/software definitions and schedule start-up support.',notes:'Modeled from offer 25-01-1787V1. Workbook evidence shows cost baseline around 71,921 EUR and a strong automation/control workload.',created:'2026-09-01',start:'2026-09-01',end:'2027-02-28',prio:'specification_and_support_control',next:'Contractual specifications attached',
    phases:[['in_progress','2026-09-01','2026-09-15',0.27,55,['Attach specifications','Confirm timing tables','Approve deliverable index'],['Specifications signed'],['Undefined requirements']],['in_progress','2026-09-16','2026-11-30',0.47,38,['Develop software logic','Build EPLAN package','Review safety logic'],['Internal design review'],['Scope interpretation']],['pending','2026-10-01','2026-11-15',0,0,['Coordinate external inputs','Prepare release pack'],['Release dependencies resolved'],['Missing customer data']],['pending','2026-12-01','2027-01-15',0,0,['Finalize code','Prepare delivery package','Pre-commissioning tests'],['Deliverables ready'],['Late change requests']],['pending','2027-01-16','2027-02-10',0,0,['Schedule support','Confirm site dates','Mobilize engineer'],['Support calendar signed'],['Site postponement']],['pending','2027-02-11','2027-02-28',0,0,['Support start-up','Close issues','Capture lessons learned'],['Acceptance test'],['Extended commissioning']]],
    ms:[['contract','Advance received','20% advance against offer 25-01-1787V1.','2026-09-15',null,'pending','Order activation',36100,20,false,false,'Sales',['Offer 25-01-1787V1','Signed scope']],['design','60-day engineering milestone','30% milestone 60 days after advance.','2026-11-15',null,'pending','Engineering & design',54150,30,false,false,'Engineering',['Engineering progress review']],['procurement','Deliverables ready for shipment','35% milestone when deliverables are ready.','2027-01-15',null,'pending','Manufacturing',63175,35,false,false,'PM',['Software package','EPLAN package']],['final','Acceptance test complete','Final 10% after acceptance test.','2027-02-28',null,'pending','FAT and commissioning',18050,10,false,false,'Commissioning',['Acceptance protocol']]],
    risks:[['Undefined specifications','Offer notes require attaching customer specifications as contractual documents.','contract','high','high',82,'Attach specs/timing tables before deep engineering.','Issue assumptions register if needed.','PM','open'],['Safety responsibility split','Ingecart retains responsibility for defining and applying safety measures.','safety','medium','high',74,'Keep safety scope explicit in engineering review.','Escalate deviations before release.','Engineering','monitoring'],['Commissioning extension','4-week start-up support may extend if site or customer conditions are not ready.','service','medium','medium',57,'Confirm site readiness and support plan in advance.','Commercially approve extra days/hours.','Field service','open']],
    gates:[['Contractual specs attached','pending','2026-09-15',null,'Specifications and timing tables attached as governing docs.','PM'],['Engineering review passed','pending','2026-11-15',null,'Software and electrical package validated internally.','Engineering'],['Deliverables ready','pending','2027-01-15',null,'Shipment-ready deliverable package completed.','PM'],['Acceptance test','pending','2027-02-28',null,'Commissioning support and acceptance completed.','Commissioning']],
    costs:[['engineering','Software engineering',36000,5600],['engineering','Electrical engineering',21500,0],['commissioning','4-week start-up support',14421.13,0]],
  },
];

const buildSuite = (cfg: any) => {
  const projectId = id('ingecart', cfg.n);
  const createdAt = ts(cfg.created);
  const phaseIds = new Map<string, string>();
  const project = { id: projectId, offer_id: null, project_number: cfg.n, title: cfg.t, customer_name: cfg.c, project_type: cfg.pt, complexity: cfg.cx, risk_level: cfg.rl, duration_category: cfg.v >= 500000 ? 'long' : 'medium', status: cfg.st, health_score: cfg.hs, scope_of_supply: cfg.scope, deliverables: cfg.deliv, exclusions: cfg.excl, contract_value: cfg.v, currency: 'EUR', payment_terms: cfg.pay, incoterms: cfg.inc, warranty_terms: cfg.war, penalties_lds: cfg.pen, customization_level: cfg.cust, engineering_complexity: cfg.eng, delivery_deadline: cfg.end, customer_requirements: cfg.req, site_constraints: cfg.src, dependencies: cfg.dep, planned_start: cfg.start, planned_end: cfg.end, actual_start: null, actual_end: null, total_budget: cfg.b, total_actual_cost: cfg.a, total_invoiced: cfg.inv, total_paid: cfg.paid, margin_target: cfg.mt, margin_actual: cfg.ma, ai_analysis: { origin: 'ingecart-curated-project-seed', priority: cfg.prio, next_control_point: cfg.next }, notes: cfg.notes, created_at: createdAt, updated_at: createdAt };
  const project_phases = cfg.phases.map((p: any, i: number) => { const phaseId = id(projectId, 'phase', String(i + 1)); phaseIds.set(N[i], phaseId); return { id: phaseId, project_id: projectId, phase_number: i + 1, phase_name: N[i], description: `${N[i]} for ${cfg.t}`, status: p[0], responsible: O[i], planned_start: p[1], planned_end: p[2], budget: Number((cfg.b * W[i]).toFixed(2)), actual_cost: Number((cfg.a * p[3]).toFixed(2)), completion_pct: p[4], key_tasks: p[5], control_points: p[6], risks: p[7], notes: '', created_at: createdAt, updated_at: createdAt }; });
  const project_milestones = cfg.ms.map((m: any, i: number) => ({ id: id(projectId, 'milestone', String(i + 1)), project_id: projectId, milestone_type: m[0], title: m[1], description: m[2], planned_date: m[3], actual_date: m[4], status: m[5], linked_phase_id: phaseIds.get(m[6]) || null, payment_amount: m[7], payment_pct: m[8], is_invoiced: Boolean(m[9]), is_paid: Boolean(m[10]), dependencies: 'Prior gate passed', gate_id: `G${i + 1}`, required_documents: m[12], responsible: m[11], notes: '', created_at: createdAt, updated_at: createdAt }));
  const project_risks = cfg.risks.map((r: any, i: number) => ({ id: id(projectId, 'risk', String(i + 1)), project_id: projectId, risk_title: r[0], description: r[1], category: r[2], probability: r[3], impact: r[4], risk_score: r[5], mitigation_action: r[6], contingency_plan: r[7], owner: r[8], status: r[9], created_at: createdAt, updated_at: createdAt }));
  const project_gates = cfg.gates.map((g: any, i: number) => ({ id: id(projectId, 'gate', String(i + 1)), project_id: projectId, gate_number: `G${i + 1}`, gate_name: g[0], status: g[1], planned_date: g[2], actual_date: g[3], description: g[4], responsible: g[5], created_at: createdAt, updated_at: createdAt }));
  const project_costs = cfg.costs.map((c: any, i: number) => ({ id: id(projectId, 'cost', String(i + 1)), project_id: projectId, category: c[0], line_item: c[1], budget_amount: c[2], actual_amount: c[3], notes: '', created_at: createdAt, updated_at: createdAt }));
  const change_orders = (cfg.changes || []).map((c: any, i: number) => ({ id: id(projectId, 'change', String(i + 1)), project_id: projectId, change_number: c[0], title: c[1], description: c[2], status: c[3], estimated_value: c[4], approved_value: c[5], impact_schedule_days: c[6], reason: c[7], created_at: createdAt, updated_at: createdAt }));
  return { project, project_phases, project_milestones, project_risks, project_gates, project_costs, change_orders };
};

export const getIngecartBundledProjectWorkspace = () => {
  const seeded = configs.map(buildSuite);
  return {
    projects: seeded.map((item) => item.project),
    project_phases: seeded.flatMap((item) => item.project_phases),
    project_milestones: seeded.flatMap((item) => item.project_milestones),
    project_risks: seeded.flatMap((item) => item.project_risks),
    project_gates: seeded.flatMap((item) => item.project_gates),
    project_costs: seeded.flatMap((item) => item.project_costs),
    change_orders: seeded.flatMap((item) => item.change_orders),
  };
};
